### ISSUE TITLE
mount overlay error

### ISSUE THREAD

**Issue by boslad** [johndah4x0r/livekit-improved#2]
There is a error in prepare_ovelayfs() when i use the code in Qemu.
The error is "mount: mountint overlay on /memory/union failed: Invalid argument"
"FatalError: Failed to prepare OverlayFS union!"
Can you bug it ? Thanks.

**Comment by johndah4x0r** [comment]
The same thing happened to me, but I managed to fix it, it is on the new "testing" branch.
Feel free to use the newer (and a bit more reliable) "testing" branch, and tell me
if something went wrong.

Thanks for testing out "Livekit-Improved"!

**Comment by johndah4x0r** [comment]
And also, I'll consider merging "testing" with "master" if everything is just as stable
as it can be.
