### ISSUE TITLE
error on line 494 of livekitlib when using in virtualbox

### ISSUE THREAD

**Issue by darylkuchay** [johndah4x0r/livekit-improved#4]
Hello and than you for this project. Was looking for a live kit that used overlay. 

I just tried to run this on a image I am building in virtualbox. I did change a value in .config and it was the iso name but the unexpected output was:

```
Changing current directory to .
./livekitlib: line: 494 syntax error nearr unexpected token 'modprobe'
./livekitlib: line: 494 '              modprobe "$MOD" 2>/dev/null'
```

I did not change anything in livekitlib as I didnt see what to align with .config. Used livekit from tomas before but I am just not sure what to change if needed. I should mention that I am using this on a non systemd arch linux derivative and testing overlayfs. Kernel is 4.17.2 and I can manually modprobe overlay with root permissions and no return comes making me think it loads the overlay kernel module. Please let me know what I am doing wrong. Thank you in advance

**Comment by johndah4x0r** [comment]
HI! I think I know this problem.
Can you provide me more info like:
* Version used
* Branch used
* OS used (I used Debian 9)
* Anything else to help me 'triangulate' the problem

FYI: The 'testing' branch is up and working, go try that out.
Thanks for reporting!

**Comment by johndah4x0r** [comment]
More dev. info:
I used a Frankenstein method and tested a Debian 9 system image ("built" with Live Kit Improved) with QEMU KVM (on CLI)

P.S: I'll consider merging 'testing' with master. (I'll report back when good news pops up)

**Comment by darylkuchay** [comment]
Thank you for your fast reply! I am trying Artix linux. artixlinux.org. Its an Arch variant with a choice for init system. I used runit but may try openrc on next try. Used Virtual box for VM and went from there installing base and base-devel giving me a build capable base install. Last night I went in to .config and tried "overlay" as that was what passed a modprobe. Same error on 494. Not sure if that is what is getting called or not but wanted to share. On report I had used overlayfs in .config. I just downloaded a zip file from archive/master last night as I stumbled on to your project on Tomas's comments section on his website. Again thank you for this effort. Ill be happy to help any way I can. Version says 1.0 at the top of build.sh. 

I ran an strace but doubt it will show much as its not a serious error:

[livekit-err.txt](https://github.com/johndah4x0r/livekit-improved/files/2152866/livekit-err.txt)

It may help. Should I try testing? Thank you again for your help!!

**Comment by darylkuchay** [comment]
Redid my attempt:

new virtualbox image - artix linux base with openrc
used wget to get your testing branch
adjusted "overlay" for unionfs type and /boot/vmlinuz-linux for kernel location 
ran ./build.sh and it seems to be working well. Watching 01-system.bund compress now.  Request for a progress bar?

Copying to usb now. 

So just to be sure, we have most of the options that Slax or Porteus has minus loading modules on the fly?
Perch is the kernel switch to activate persistent storage 
We can save sessions to modules 

If all this is true, hats off to you. Great job! This allows one to build packages and custom tailor a usb stick to their needs. 

I'm hoping we can boot from ISO file as with a rolling distribution i would rather swap the base ISO and rebuild modules say 4 times a year rather than rebuild starting here each time?

**Comment by darylkuchay** [comment]
In trying the usb I had to edit syslinux.cfg to add the affix on the artix kernel. It found the right folder but the vmlinuz-linux was not in the grub boot line. vmlinuz was so that was an easy get around. Shortly in to boot no matter the boot option I get kernel panic as indications are that no syncing due to being unable to mount rootfs on block 2.0. I know thats not much but hopefully a breadcrumb. Please let me know if I can provide more.

**Comment by johndah4x0r** [comment]
You should try testing, since it has the latest fix.
Thanks for trying out!

**Comment by darylkuchay** [comment]
I downloaded from testing to produce the above results. Think it was how I was able to get past build issue. ISO goes in to kernel panic on boot not able to mount
